ONE_UNIQUE_VAL = ["EXTERNALCREATIVEID"]
# All distinct values are in test set
TEST_SET_ALL = ["UA_DEVICETYPE", "DEVICEORIENTATION", "UA_BROWSERRENDERINGENGINE", "ACTUALDEVICETYPE", "PLATFORM",
                "INTENDEDDEVICETYPE", "CDNNAME", "EXTERNALADSERVER",
                "ACCOUNTID", "CREATIVETYPE", "UA_OS", "SDK"]  # + "GEOIP_METROCODE", "GEOIP_DMACODE",
ALL_CATEGORIES = ["ACCOUNTID", "CAMPAIGNID", "PLACEMENTID", "CREATIVEID", "CREATIVETYPE",

                  "PLATFORM", "PLATFORMVERSION", "INTENDEDDEVICETYPE", "ACTUALDEVICETYPE",

                  "DEVICEORIENTATION", "SDK", "NETWORKTYPE", "CDNNAME",

                  "EXTERNALADSERVER", "EXTERNALPLACEMENTID", "EXTERNALSITEID",
                  "EXTERNALSUPPLIERID",

                  "GEOIP_TIMEZONE", "GEOIP_COUNTRY", "GEOIP_REGION", "GEOIP_CITY", "GEOIP_AREACODE",
                  "GEOIP_METROCODE", "GEOIP_DMACODE",

                  "UA_HARDWARETYPE", "UA_DEVICETYPE", "UA_PLATFORM", "UA_PLATFORMVERSION",
                  "UA_VENDOR", "UA_MODEL", "UA_OS", "UA_OSVERSION", "UA_BROWSER", "UA_BROWSERVERSION",
                  "UA_BROWSERRENDERINGENGINE"
                  ]

CATEGORIES_LARGE = ["CAMPAIGNID", "PLACEMENTID", "CREATIVEID", "PLATFORMVERSION", "EXTERNALPLACEMENTID", "EXTERNALSITEID",
                "GEOIP_TIMEZONE", "GEOIP_REGION", "GEOIP_CITY", "GEOIP_AREACODE",
                  "GEOIP_METROCODE", "GEOIP_DMACODE", "UA_HARDWARETYPE", "UA_PLATFORM", "UA_PLATFORMVERSION",
                "UA_VENDOR", "UA_MODEL", "UA_OSVERSION", "UA_BROWSER", "UA_BROWSERVERSION",
                  "UA_BROWSERRENDERINGENGINE"]

BINARY = ["UA_MOBILEDEVICE"]
ALL_CONTINIOUS = ["TOPMOSTREACHABLEWINDOWHEIGHT", "TOPMOSTREACHABLEWINDOWWIDTH", "HOSTWINDOWHEIGHT", "HOSTWINDOWWIDTH"]
JSON = ["FILESJSON", "ERRORSJSON"]
TIMESTAMPS = ["TIMESTAMP"] + ["timestamp_dayofmonth", "timestamp_dayofweek", "timestamp_hour", "timestamp_minute",
                              "timestamp_second", "timestamp_milisecond","timestamp_alteranivestamp"]
GEO = ["GEOIP_LNG", "GEOIP_LAT", "GEOIP_SUM", "GEOIP_PROD", "GEOIP_DIFF"]

TARGET = "ADLOADINGTIME"
